### ISSUE TITLE
System.InvalidCastException 

### ISSUE THREAD

**Issue by liemdt1811** [ToCSharp/TypeScriptAST#3]
Hi there,
    I got this System.InvalidCastException _**Cannot cast 'Zu.TypeScript.TsTypes.NamedImports' to 'Zu.TypeScript.TsTypes.INamedImportBindings'**_ 
    when i try to parse the following code:
    `import { Component, HostBinding } from '@angular/core';`

Thanks

**Comment by dezrtluver** [comment]
I fixed it with this:

`public class NamedImports : Node, INamedImportsOrExports, INamedImportBindings
{
...
}
`

**Comment by ToCSharp** [comment]
This is old project for TypeScript, which is developing so fast. My main task was to make parser for JavaScript to AST. I think now is not the best option for parsing TypeScript. Now it's not easy to upgrade to the current TypeScript. Maybe when I have more time
